# Generated by Django 4.0.1 on 2022-01-21 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license_plate_web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='name',
        ),
    ]
